### ISSUE TITLE
Detection of target overlap with the guided pose is not always successful

### ISSUE THREAD

**Issue by Acwok** [paroj/pose_calib#6]
The function `pose_close_to_tgt()` struggles sometimes, see: https://youtu.be/xFR-GWuf3MQ.  
It generally happens when the board has a big angle like in the video.

The value displayed in the terminal correspond to the `jaccard` variable here: https://github.com/paroj/pose_calib/blob/639bd19220df8ef7d650d8803198f43b154e3785/ui.py#L160

**Comment by paroj** [comment]
the issue apparent in your video is inaccurate bootstrapping, i.e. the projected board is smaller than in the video. You can see it faintly in the grey area of the jaccard window.
See Section 3.4 of the paper for details on bootstrapping.

**Comment by Acwok** [comment]
> You can see it faintly in the grey area of the jaccard window.  

Indeed, I can see it now, through the grey area.  
If I understand correctly, the first single frame calibration wasn't great.    
If I make correspond the white and grey areas in the jaccard window, the calibration can continue and outputs good results though.
